
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diky
 */
public class ChangePIN extends javax.swing.JFrame {
    int vis1=0, vis2=0;
    /**
     * Creates new form Register
     */
    public ChangePIN() {
        initComponents();
    }
    
    String NIM, ap, ab;
    int PIN, newPIN;
    
    void setData(String nim, int pin){
        NIM = nim;
        PIN = pin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirm = new javax.swing.JLabel();
        Panel_Icon = new javax.swing.JPanel();
        ic_oldPin = new javax.swing.JLabel();
        ic_pin1 = new javax.swing.JLabel();
        ic_pin2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textPIN = new javax.swing.JPasswordField();
        textPIN2 = new javax.swing.JPasswordField();
        btnShow1 = new javax.swing.JLabel();
        textOldPIN = new javax.swing.JPasswordField();
        panel_back = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANK DIGITAL");
        getContentPane().setLayout(null);

        btnConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirm.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn.png")); // NOI18N
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmMouseExited(evt);
            }
        });
        getContentPane().add(btnConfirm);
        btnConfirm.setBounds(20, 400, 310, 80);

        Panel_Icon.setOpaque(false);

        ic_oldPin.setToolTipText("NIM");

        ic_pin1.setToolTipText("PIN");

        ic_pin2.setToolTipText("Confirm PIN");

        javax.swing.GroupLayout Panel_IconLayout = new javax.swing.GroupLayout(Panel_Icon);
        Panel_Icon.setLayout(Panel_IconLayout);
        Panel_IconLayout.setHorizontalGroup(
            Panel_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IconLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ic_oldPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ic_pin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_IconLayout.createSequentialGroup()
                        .addComponent(ic_pin2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_IconLayout.setVerticalGroup(
            Panel_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IconLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ic_oldPin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(ic_pin1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(ic_pin2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Panel_Icon);
        Panel_Icon.setBounds(30, 150, 40, 230);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        textPIN.setBackground(new java.awt.Color(255, 255, 255));
        textPIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPIN.setBorder(null);

        textPIN2.setBackground(new java.awt.Color(255, 255, 255));
        textPIN2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPIN2.setBorder(null);

        btnShow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShow1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_1.jpg")); // NOI18N
        btnShow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShow1MouseClicked(evt);
            }
        });

        textOldPIN.setBackground(new java.awt.Color(255, 255, 255));
        textOldPIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textOldPIN.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(textOldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textPIN2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textPIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(textOldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(textPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPIN2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 140, 280, 260);

        panel_back.setOpaque(false);

        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_backLayout = new javax.swing.GroupLayout(panel_back);
        panel_back.setLayout(panel_backLayout);
        panel_backLayout.setHorizontalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panel_backLayout.setVerticalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel_back);
        panel_back.setBounds(10, 10, 40, 40);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Change-PIN.png")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 350, 500);

        setBounds(1550, 200, 366, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseEntered
        // TODO add your handling code here:
        ImageIcon confirm = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn-2.png");
        btnConfirm.setIcon(confirm);
    }//GEN-LAST:event_btnConfirmMouseEntered

    private void btnConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseExited
        // TODO add your handling code here:
        ImageIcon confirm = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn.png");
        btnConfirm.setIcon(confirm);
        
    }//GEN-LAST:event_btnConfirmMouseExited

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
        // TODO add your handling code here:
        checkPIN(); 
    }//GEN-LAST:event_btnConfirmMouseClicked

    private void btnShow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShow1MouseClicked
        // TODO add your handling code here:
        if(vis1==0){
            textPIN.setEchoChar((char)0);
            textPIN2.setEchoChar((char)0);
            ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_2.jpg");
            btnShow1.setIcon(ic);
            vis1=1;
        }
        else {
            textPIN.setEchoChar('*');
            textPIN2.setEchoChar('*');
            ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_1.jpg");
            btnShow1.setIcon(ic);
            vis1=0;
        }
    }//GEN-LAST:event_btnShow1MouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Home home =  new Home();
        home.setData(NIM);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePIN().setVisible(true);
            }
        });
    }
    
    void checkPIN(){
        if(Arrays.equals(textPIN.getPassword(), textPIN2.getPassword())){
            ap = new String(textOldPIN.getPassword());
            ab = new String(textPIN2.getPassword());
            int arrPIN = Integer.parseInt(ap);
            if(PIN==arrPIN){
                    dataBank data = new dataBank();
                    data.updatePINtoDatabase(ab, NIM);
                    JOptionPane.showMessageDialog(null, "Pin Berhasil diubah");
                    Login_Menu login = new Login_Menu();
                    login.setVisible(true);
                    dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Pin anda Salah");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "PIN anda salah");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Panel_Icon;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnConfirm;
    private javax.swing.JLabel btnShow1;
    private javax.swing.JLabel ic_oldPin;
    private javax.swing.JLabel ic_pin1;
    private javax.swing.JLabel ic_pin2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPasswordField textOldPIN;
    private javax.swing.JPasswordField textPIN;
    private javax.swing.JPasswordField textPIN2;
    // End of variables declaration//GEN-END:variables
}
