/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 *
 * @author Diky
 */
public class Home extends javax.swing.JFrame {
    String Nama, NIM, Saldo;
    int PIN;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    void setData(String nm){
        NIM = nm;
        dataBank data = new dataBank();
        data.getData(nm);
        Nama = data.Nama;
        Saldo = data.Saldo;
        PIN = data.PIN;
        textNama.setText(Nama);
        textNIM.setText(NIM); 
        setRupiah(Saldo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNama = new javax.swing.JLabel();
        textNIM = new javax.swing.JLabel();
        btnTransfer = new javax.swing.JLabel();
        btnPayment = new javax.swing.JLabel();
        btnReports = new javax.swing.JLabel();
        btnPIN = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANK DIGITAL");
        getContentPane().setLayout(null);

        textSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textSaldo.setForeground(new java.awt.Color(255, 255, 255));
        textSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSaldo.setText("Balance");
        textSaldo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(textSaldo);
        textSaldo.setBounds(30, 290, 290, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Account Balance");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 190, 290, 16);

        textNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textNama.setForeground(new java.awt.Color(255, 255, 255));
        textNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textNama.setText("NAMA");
        getContentPane().add(textNama);
        textNama.setBounds(30, 220, 290, 30);

        textNIM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textNIM.setForeground(new java.awt.Color(255, 255, 255));
        textNIM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textNIM.setText("NIM");
        textNIM.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(textNIM);
        textNIM.setBounds(30, 260, 290, 25);

        btnTransfer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTransfer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Transfer.png")); // NOI18N
        btnTransfer.setAlignmentY(0.0F);
        btnTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransfer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransferMouseExited(evt);
            }
        });
        getContentPane().add(btnTransfer);
        btnTransfer.setBounds(10, 370, 160, 40);

        btnPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPayment.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Payment.png")); // NOI18N
        btnPayment.setAlignmentY(0.0F);
        btnPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentMouseExited(evt);
            }
        });
        getContentPane().add(btnPayment);
        btnPayment.setBounds(180, 370, 160, 40);

        btnReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReports.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Reports.png")); // NOI18N
        btnReports.setAlignmentY(0.0F);
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
        });
        getContentPane().add(btnReports);
        btnReports.setBounds(180, 420, 160, 40);

        btnPIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPIN.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-ChangePin.png")); // NOI18N
        btnPIN.setAlignmentY(0.0F);
        btnPIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPIN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPINMouseExited(evt);
            }
        });
        getContentPane().add(btnPIN);
        btnPIN.setBounds(10, 420, 160, 40);

        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 30, 30, 30);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Home .jpg")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 350, 500);

        setBounds(1550, 200, 366, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseEntered
        // TODO add your handling code here:
        ImageIcon pay_enter = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Payment-2.png");
        btnPayment.setIcon(pay_enter);
    }//GEN-LAST:event_btnPaymentMouseEntered

    private void btnPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseExited
        // TODO add your handling code here:
        ImageIcon pay_exit= new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Payment.png");
        btnPayment.setIcon(pay_exit);
    }//GEN-LAST:event_btnPaymentMouseExited

    private void btnTransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferMouseEntered
        // TODO add your handling code here:
        ImageIcon transfer = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-transfer-2.png");
        btnTransfer.setIcon(transfer);
    }//GEN-LAST:event_btnTransferMouseEntered

    private void btnTransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferMouseExited
        // TODO add your handling code here:
        ImageIcon transfer = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-transfer.png");
        btnTransfer.setIcon(transfer);
    }//GEN-LAST:event_btnTransferMouseExited

    private void btnPINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMouseEntered
        // TODO add your handling code here:
        ImageIcon pin = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-ChangePin-2.png");
        btnPIN.setIcon(pin);
    }//GEN-LAST:event_btnPINMouseEntered

    private void btnPINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMouseExited
        // TODO add your handling code here:
        ImageIcon pin = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-ChangePin.png");
        btnPIN.setIcon(pin);
    }//GEN-LAST:event_btnPINMouseExited

    private void btnReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseEntered
        // TODO add your handling code here:
        ImageIcon report = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Reports-2.png");
        btnReports.setIcon(report);
    }//GEN-LAST:event_btnReportsMouseEntered

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        // TODO add your handling code here:
        ImageIcon report = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Reports.png");
        btnReports.setIcon(report);
    }//GEN-LAST:event_btnReportsMouseExited

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                   "Ingin Keluar?", 
                    "Keluar", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(jawab == JOptionPane.YES_OPTION){
            Login_Menu login = new Login_Menu();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnPINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMouseClicked
        // TODO add your handling code here:
        ChangePIN pin = new ChangePIN();
        pin.setData(NIM, PIN);
        pin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPINMouseClicked

    private void btnPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseClicked
        // TODO add your handling code here:
        Payment pay = new Payment();
        pay.setData(NIM);
        pay.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPaymentMouseClicked

    private void btnTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferMouseClicked
        // TODO add your handling code here:
        Transfer transfer = new Transfer();
        transfer.setData(NIM, Nama, Saldo);
        transfer.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTransferMouseClicked

    private void btnReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseClicked
        // TODO add your handling code here:
        Report report = new Report();
        report.setData(NIM);
        report.loadDatabase(Nama);
        report.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReportsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    void setRupiah(String n){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        textSaldo.setText("Balance : " + kursIndonesia.format(Integer.parseInt(n)));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnPIN;
    private javax.swing.JLabel btnPayment;
    private javax.swing.JLabel btnReports;
    private javax.swing.JLabel btnTransfer;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel textNIM;
    private javax.swing.JLabel textNama;
    private javax.swing.JLabel textSaldo;
    // End of variables declaration//GEN-END:variables
}
