
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diky
 */
public class Register extends javax.swing.JFrame {
    int vis1=0, vis2=0, flag=0;
    Connection connection;
    Statement statement;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JLabel();
        Panel_Icon = new javax.swing.JPanel();
        ic_name = new javax.swing.JLabel();
        ic_nim = new javax.swing.JLabel();
        ic_pin1 = new javax.swing.JLabel();
        ic_pin2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textNama = new javax.swing.JTextField();
        textNIM = new javax.swing.JTextField();
        textPIN = new javax.swing.JPasswordField();
        textPIN2 = new javax.swing.JPasswordField();
        btnShow1 = new javax.swing.JLabel();
        btnShow2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANK DIGITAL");
        getContentPane().setLayout(null);

        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 20, 20, 20);

        btnConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirm.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn.png")); // NOI18N
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmMouseExited(evt);
            }
        });
        getContentPane().add(btnConfirm);
        btnConfirm.setBounds(20, 400, 310, 80);

        Panel_Icon.setOpaque(false);

        ic_name.setToolTipText("Nama");

        ic_nim.setToolTipText("NIM");

        ic_pin1.setToolTipText("PIN");

        ic_pin2.setToolTipText("Confirm PIN");

        javax.swing.GroupLayout Panel_IconLayout = new javax.swing.GroupLayout(Panel_Icon);
        Panel_Icon.setLayout(Panel_IconLayout);
        Panel_IconLayout.setHorizontalGroup(
            Panel_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IconLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_IconLayout.createSequentialGroup()
                        .addComponent(ic_pin1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_IconLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Panel_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ic_nim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ic_pin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ic_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        Panel_IconLayout.setVerticalGroup(
            Panel_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ic_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(ic_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ic_pin1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(ic_pin2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Panel_Icon);
        Panel_Icon.setBounds(30, 150, 40, 230);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        textNama.setBackground(new java.awt.Color(255, 255, 255));
        textNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textNama.setBorder(null);

        textNIM.setBackground(new java.awt.Color(255, 255, 255));
        textNIM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textNIM.setBorder(null);

        textPIN.setBackground(new java.awt.Color(255, 255, 255));
        textPIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPIN.setBorder(null);
        textPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPINKeyPressed(evt);
            }
        });

        textPIN2.setBackground(new java.awt.Color(255, 255, 255));
        textPIN2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPIN2.setBorder(null);
        textPIN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPIN2KeyPressed(evt);
            }
        });

        btnShow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShow1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_1.jpg")); // NOI18N
        btnShow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShow1MouseClicked(evt);
            }
        });

        btnShow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShow2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_1.jpg")); // NOI18N
        btnShow2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShow2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPIN2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShow2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnShow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNama, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(textNIM))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(textNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPIN2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShow2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 140, 250, 260);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Login (1).jpg")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 350, 500);

        setBounds(1550, 200, 366, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseEntered
        // TODO add your handling code here:
        ImageIcon confirm = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn-2.png");
        btnConfirm.setIcon(confirm);
    }//GEN-LAST:event_btnConfirmMouseEntered

    private void btnConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseExited
        // TODO add your handling code here:
        ImageIcon confirm = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn.png");
        btnConfirm.setIcon(confirm);
        
    }//GEN-LAST:event_btnConfirmMouseExited

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
        // TODO add your handling code here:
        if(
                textNama.getText().equals("") ||
                textNIM.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tolong lengkapi data anda");
        }
        else {
            cekIfNimExist();
        }
        
    }//GEN-LAST:event_btnConfirmMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Login_Menu login = new Login_Menu();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void textPINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPINKeyPressed
        // TODO add your handling code here:
        String value = textPIN.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            textPIN.setEditable(true);
        } else {
            textPIN.setEditable(false);
            JOptionPane.showMessageDialog(null, "Hanya Angka yang diperbolehkan");
        }
        if(l>5){
            textPIN.setEnabled(false);
        }
    }//GEN-LAST:event_textPINKeyPressed

    private void textPIN2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPIN2KeyPressed
        // TODO add your handling code here:
        String value = textPIN2.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            textPIN2.setEditable(true);
        } else {
            textPIN2.setEditable(false);
            JOptionPane.showMessageDialog(null, "Hanya Angka yang diperbolehkan");
        }
        if(l>5){
            textPIN2.setEnabled(false);
        }
    }//GEN-LAST:event_textPIN2KeyPressed

    private void btnShow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShow1MouseClicked
        // TODO add your handling code here:
        if(vis1==0){
            textPIN.setEchoChar((char)0);
            ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_2.jpg");
            btnShow1.setIcon(ic);
            vis1=1;
        }
        else {
            textPIN.setEchoChar('*');
            ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_1.jpg");
            btnShow1.setIcon(ic);
            vis1=0;
        }
    }//GEN-LAST:event_btnShow1MouseClicked

    private void btnShow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShow2MouseClicked
        // TODO add your handling code here:
        if(vis2==0){
            textPIN2.setEchoChar((char)0);
            ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_2.jpg");
            btnShow2.setIcon(ic);
            vis2=1;
        }
        else {
            textPIN2.setEchoChar('*');
            ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\visibility_1.jpg");
            btnShow2.setIcon(ic);
            vis2=0;
        }
    }//GEN-LAST:event_btnShow2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    
    void refresh(){
        textNama.setText("");
        textNIM.setText("");
        textPIN.setText("");
        textPIN2.setText(""); 
        textPIN.setEnabled(true);
        textPIN2.setEnabled(true);
    }
    
    public void comparePassword(){
        dataBank data = new dataBank();
        if(textPIN.getPassword().length==6){
            if(Arrays.equals(textPIN.getPassword(), textPIN2.getPassword())){
                int jawab = JOptionPane.showOptionDialog(this, 
                    "Apakah data anda sudah benar?", 
                    "Konfirmasi", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
                if(jawab == JOptionPane.YES_OPTION){
                    AfterRegister after = new AfterRegister();
                    String pn = new String(textPIN.getPassword());
                    data.addDataToDatabase(pn, textNama.getText(), textNIM.getText());
                    JOptionPane.showMessageDialog(this, "Account has been created successfully");
                    after.setData(textNIM.getText(), "0");
                    after.setVisible(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "PIN Tidak Sama");
                textPIN.setEnabled(true);
                textPIN2.setEnabled(true);
                textPIN.setText("");
                textPIN2.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "PIN harus 6 Angka");
        }
    }
    
    
    void cekIfNimExist(){
        String nim = new String(textNIM.getText());
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_sederhana", "Diky", "Dikypass123");
            statement = (Statement) connection.createStatement();
            String NM = "SELECT * FROM `data` WHERE NIM='"+textNIM.getText()+"'";
            ResultSet resultSet = statement.executeQuery(NM);
            
            while (resultSet.next()) {
                String NIM = resultSet.getString("NIM");
                if(nim.equalsIgnoreCase(NIM)){
                    JOptionPane.showMessageDialog(null, "NIM Sudah Terdaftar");
                    refresh();
                    flag=1;
                }
            }
            if (flag == 0) {
                comparePassword();
            }
            
        } 
        catch(SQLException throwables){
            throwables.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Panel_Icon;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnConfirm;
    private javax.swing.JLabel btnShow1;
    private javax.swing.JLabel btnShow2;
    private javax.swing.JLabel ic_name;
    private javax.swing.JLabel ic_nim;
    private javax.swing.JLabel ic_pin1;
    private javax.swing.JLabel ic_pin2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textNIM;
    private javax.swing.JTextField textNama;
    private javax.swing.JPasswordField textPIN;
    private javax.swing.JPasswordField textPIN2;
    // End of variables declaration//GEN-END:variables
}
