
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diky
 */
public class Transfer extends javax.swing.JFrame {
    Connection connection;//Creating object of Connection class
    Statement statement;//Creating object of Statement class
    
    String Saldo, NIM, Nama, menu="", receiverSaldo="";
    int PIN, sw=-0, flag = 0, sufficient=0;
    
    /**
     * Creates new form Payment
     */
    public Transfer() {
        initComponents();
        panel_switch.setVisible(false);
        btnConfirm.setVisible(false);
    }
    
    void setData(String nim, String nama, String saldo){
        Nama = nama;
        NIM = nim;
        Saldo = saldo;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_switch = new javax.swing.JPanel();
        textTransfer = new javax.swing.JTextField();
        textAmount = new javax.swing.JTextField();
        line1 = new javax.swing.JLabel();
        line2 = new javax.swing.JLabel();
        btnOwn = new javax.swing.JLabel();
        btnOther = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANK DIGITAL");
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        panel_switch.setOpaque(false);
        panel_switch.setLayout(null);

        textTransfer.setBackground(new java.awt.Color(245, 245, 245));
        textTransfer.setBorder(null);
        panel_switch.add(textTransfer);
        textTransfer.setBounds(40, 110, 260, 30);

        textAmount.setBackground(new java.awt.Color(245, 245, 245));
        textAmount.setBorder(null);
        panel_switch.add(textAmount);
        textAmount.setBounds(40, 30, 260, 30);

        line1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\line-transferTo.png")); // NOI18N
        panel_switch.add(line1);
        line1.setBounds(20, 90, 310, 65);

        line2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\line-Amount.png")); // NOI18N
        panel_switch.add(line2);
        line2.setBounds(20, 10, 310, 65);

        btnOwn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Transfer-acc.png")); // NOI18N
        btnOwn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOwnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOwnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOwnMouseExited(evt);
            }
        });

        btnOther.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Transfer-other.png")); // NOI18N
        btnOther.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOther.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOtherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOtherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOtherMouseExited(evt);
            }
        });

        btnConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirm.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn.png")); // NOI18N
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_switch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOwn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOther)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOther)
                    .addComponent(btnOwn))
                .addGap(18, 18, 18)
                .addComponent(panel_switch, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 70, 330, 420);

        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 20, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Transfer.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 500);

        setBounds(1550, 200, 366, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        Home home =  new Home();
        home.setData(NIM);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnOwnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOwnMouseEntered
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Transfer-acc-2.png");
        btnOwn.setIcon(ic);
    }//GEN-LAST:event_btnOwnMouseEntered

    private void btnOwnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOwnMouseExited
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Transfer-acc.png");
        btnOwn.setIcon(ic);
    }//GEN-LAST:event_btnOwnMouseExited

    private void btnOtherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtherMouseEntered
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Transfer-other-2.png");
        btnOther.setIcon(ic);
    }//GEN-LAST:event_btnOtherMouseEntered

    private void btnOtherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtherMouseExited
        // TODO add your handling code here:
        ImageIcon ic = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\btn-Transfer-other.png");
        btnOther.setIcon(ic);
    }//GEN-LAST:event_btnOtherMouseExited

    private void btnOwnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOwnMouseClicked
        // TODO add your handling code here:
        toggleMenu(true, false, false, "own");
    }//GEN-LAST:event_btnOwnMouseClicked

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
        // TODO add your handling code here:
        checkMenu();
    }//GEN-LAST:event_btnConfirmMouseClicked

    private void btnConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseEntered
        // TODO add your handling code here:
        ImageIcon confirm = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn-2.png");
        btnConfirm.setIcon(confirm);
    }//GEN-LAST:event_btnConfirmMouseEntered

    private void btnConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseExited
        // TODO add your handling code here:
        ImageIcon confirm = new ImageIcon("C:\\Users\\Irfan\\Documents\\NetBeansProjects\\Project_Kuliah\\img\\Register-btn.png");
        btnConfirm.setIcon(confirm);

    }//GEN-LAST:event_btnConfirmMouseExited

    private void btnOtherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtherMouseClicked
        // TODO add your handling code here:
        toggleMenu(true, true, true, "other");
    }//GEN-LAST:event_btnOtherMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }
    
    
    void getDataFromOwnAccount(){
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_sederhana", "Diky", "Dikypass123");//Crating connection with database
            statement = (Statement) connection.createStatement();//crating statement object
            String NM = "SELECT * FROM `data` WHERE NIM='"+NIM+"'";//Storing MySQL query in A string variable
            ResultSet resultSet = statement.executeQuery(NM);
            
            while (resultSet.next()) {
                String Sld = resultSet.getString("Saldo");
                int jumlah = Integer.parseInt(Sld)+Integer.parseInt(textAmount.getText());
                Saldo = Integer.toString(jumlah);
            }           
        } 
        catch(SQLException throwables){
            throwables.printStackTrace();
        }
    }
    
    void getDataFromOtherAccount(){
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_sederhana", "Diky", "Dikypass123");//Crating connection with database
            statement = (Statement) connection.createStatement();//crating statement object
            String NM = "SELECT * FROM `data` WHERE NIM='"+textTransfer.getText()+"'";//Storing MySQL query in A string variable
            ResultSet resultSet = statement.executeQuery(NM);
            
            while (resultSet.next()) {
                String nim = resultSet.getString("NIM");
                String nama = resultSet.getString("Nama");
                if(textTransfer.getText().equalsIgnoreCase(nim)){
                    flag = 1;
                    String sld = resultSet.getString("Saldo");
                    checkIfSaldoSufficent(Saldo);
                    if(sufficient==1){
                        int jumlah = Integer.parseInt(sld)+Integer.parseInt(textAmount.getText());
                        receiverSaldo = Integer.toString(jumlah);
                        updateSaldo(receiverSaldo, textTransfer.getText());
                        toReports(nama, Nama, textAmount.getText());
                        JOptionPane.showMessageDialog(null, "Transfer Berhasil");
                    }
                    else{
                        break;
                    }
                }
                else{
                    break;
                }
            }
            if (flag == 0) {
                JOptionPane.showMessageDialog(null, "Akun tidak ada..");//When invalid username is entered
            }
        } 
        catch(SQLException throwables){
            throwables.printStackTrace();
        }
    }
    
    void updateSaldo(Object a, Object b){
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm_sederhana", "Diky", "Dikypass123");
            statement = (Statement) connection.createStatement();
            String NM = "UPDATE `data` SET `Saldo`='"+a+"' WHERE NIM='"+b+"'";
            statement.execute(NM);
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    void checkMenu(){
        if(menu=="own"){
            getDataFromOwnAccount();
            updateSaldo(Saldo, NIM);
            toReports(Nama, Nama, textAmount.getText());
            JOptionPane.showMessageDialog(null, "Transfer Berhasil");
        }
        else{
            getDataFromOtherAccount();        
        }
    }
    
    void checkIfSaldoSufficent(String sld){
        int saldo = Integer.parseInt(sld);
        int saldo1 = Integer.parseInt(textAmount.getText());
        if(saldo<saldo1){
            JOptionPane.showMessageDialog(null, "The balance is not sufficient");
        }
        else{
            int jumlah = saldo-saldo1;
            Saldo = Integer.toString(jumlah);
            updateSaldo(Saldo, NIM);
            sufficient=1;
        }
    }
    
    void toReports(String recepient, String sender, String amount){
        try{
            String report = "INSERT INTO reports VALUES (0,'"+sender+"','"+recepient+"','"+amount+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(report);
            pst.execute();
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    void toggleMenu(Boolean panel, Boolean text, Boolean line, String mn){
        panel_switch.setVisible(panel);
        textTransfer.setVisible(text);
        line1.setVisible(line); 
        btnConfirm.setVisible(true);
        menu = mn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnConfirm;
    private javax.swing.JLabel btnOther;
    private javax.swing.JLabel btnOwn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line2;
    private javax.swing.JPanel panel_switch;
    private javax.swing.JTextField textAmount;
    private javax.swing.JTextField textTransfer;
    // End of variables declaration//GEN-END:variables
}
